server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ??????????? dianca_db
    url: jdbc:mysql://127.0.0.1:3306/dianca_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 327510 # ?? ?????????? VS Code?????????

# MyBatis-Plus ??
mybatis-plus:
  configuration:
    # ??????? SQL????????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # ??????????? Java ????????? (?? table_number -> tableNumber)
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # ????????
      id-type: auto